/*
 * PinConfiguration.h
 *
 * Created: 20-09-14 2:21:55 PM
 *  Author: Klocman
 */ 


#ifndef PINCONFIGURATION_H_
#define PINCONFIGURATION_H_

#define SEVSEG_A_PIN PINB4
#define SEVSEG_A_PORT PORTB
#define SEVSEG_A_DDR DDRB
#define SEVSEG_B_PIN PIND7
#define SEVSEG_B_PORT PORTD
#define SEVSEG_B_DDR DDRD
#define SEVSEG_C_PIN PINC4
#define SEVSEG_C_PORT PORTC
#define SEVSEG_C_DDR DDRC
#define SEVSEG_D_PIN PINC2
#define SEVSEG_D_PORT PORTC
#define SEVSEG_D_DDR DDRC
#define SEVSEG_E_PIN PINC1
#define SEVSEG_E_PORT PORTC
#define SEVSEG_E_DDR DDRC
#define SEVSEG_F_PIN PINB3
#define SEVSEG_F_PORT PORTB
#define SEVSEG_F_DDR DDRB
#define SEVSEG_G_PIN PINC5
#define SEVSEG_G_PORT PORTC
#define SEVSEG_G_DDR DDRC
#define SEVSEG_DP_PIN PINC3
#define SEVSEG_DP_PORT PORTC
#define SEVSEG_DP_DDR DDRC

#define MULTIPLEX_1_PIN PINB2
#define MULTIPLEX_2_PIN PINB1
#define MULTIPLEX_3_PIN PINB0
#define MULTIPLEX_1_DDR DDRB
#define MULTIPLEX_2_DDR DDRB
#define MULTIPLEX_3_DDR DDRB
#define MULTIPLEX_1_PORT PORTB
#define MULTIPLEX_2_PORT PORTB
#define MULTIPLEX_3_PORT PORTB

#define BUTTON_ADC 7

#define SENSOR_PIN PIND3
#define SENSOR_DDR DDRD
#define SENSOR_PORT PORTD
#define SENSOR_PORT_IN PIND

#define SPEAKER_PIN PIND2
#define SPEAKER_DDR DDRD
#define SPEAKER_PORT PORTD

#define TRIAC_HUM_PIN PINB5
#define TRIAC_HUM_DDR DDRB
#define TRIAC_HUM_PORT PORTB
#define TRIAC_TEMP_PORT PORTC
#define TRIAC_TEMP_DDR DDRC
#define TRIAC_TEMP_PIN PINC0

#define LEDS_1_PIN PIND4
#define LEDS_2_PIN PIND6
#define LEDS_3_PIN PIND5
#define LEDS_1_DDR DDRD
#define LEDS_2_DDR DDRD
#define LEDS_3_DDR DDRD
#define LEDS_1_PORT PORTD
#define LEDS_2_PORT PORTD
#define LEDS_3_PORT PORTD

#define OUTPUT_TRANSMIT_PIN PIND1
#define OUTPUT_TRANSMIT_DDR DDRD
#define OUTPUT_RECEIVE_PIN PIND0
#define OUTPUT_RECEIVE_DDR DDRD
#define OUTPUT_RECEIVE_PORT PORTD


#endif /* PINCONFIGURATION_H_ */