/*
 * PinConfiguration.h
 *
 * Created: 20-09-14 2:21:55 PM
 *  Author: Klocman
 */ 


#ifndef PINCONFIGURATION_H_
#define PINCONFIGURATION_H_

#define SEVSEG_A_PIN PIND3
#define SEVSEG_A_PORT PORTD
#define SEVSEG_A_DDR DDRD
#define SEVSEG_B_PIN PINB6
#define SEVSEG_B_PORT PORTB
#define SEVSEG_B_DDR DDRB
#define SEVSEG_C_PIN PINC1
#define SEVSEG_C_PORT PORTC
#define SEVSEG_C_DDR DDRC
#define SEVSEG_D_PIN PINC3
#define SEVSEG_D_PORT PORTC
#define SEVSEG_D_DDR DDRC
#define SEVSEG_E_PIN PINC4
#define SEVSEG_E_PORT PORTC
#define SEVSEG_E_DDR DDRC
#define SEVSEG_F_PIN PIND4
#define SEVSEG_F_PORT PORTD
#define SEVSEG_F_DDR DDRD
#define SEVSEG_G_PIN PINC0
#define SEVSEG_G_PORT PORTC
#define SEVSEG_G_DDR DDRC
#define SEVSEG_DP_PIN PINC2
#define SEVSEG_DP_PORT PORTC
#define SEVSEG_DP_DDR DDRC

#define MULTIPLEX_1_PIN PIND2
#define MULTIPLEX_2_PIN PIND5
#define MULTIPLEX_3_PIN PINB7
#define MULTIPLEX_1_DDR DDRD
#define MULTIPLEX_2_DDR DDRD
#define MULTIPLEX_3_DDR DDRB
#define MULTIPLEX_1_PORT PORTD
#define MULTIPLEX_2_PORT PORTD
#define MULTIPLEX_3_PORT PORTB

#define BUTTON_1_PIN PINB5
#define BUTTON_1_PORT PORTB
#define BUTTON_1_DDR DDRB
#define BUTTON_1_PININ PINB
#define BUTTON_2_PIN PINB3
#define BUTTON_2_PORT PORTB
#define BUTTON_2_DDR DDRB
#define BUTTON_2_PININ PINB

#define SENSOR_PIN PINB4
#define SENSOR_DDR DDRB
#define SENSOR_PORT PORTB
#define SENSOR_PORT_IN PINB

#define SPEAKER_PIN PINB2
#define SPEAKER_DDR DDRB
#define SPEAKER_PORT PORTB

#define TRIAC_TEMP_PIN PINC5
#define TRIAC_HUM_PIN PINB0
#define TRIAC_TEMP_DDR DDRC
#define TRIAC_HUM_DDR DDRB
#define TRIAC_TEMP_PORT PORTC
#define TRIAC_HUM_PORT PORTB

#define LEDS_1_PIN PINB1
#define LEDS_2_PIN PIND6
#define LEDS_3_PIN PIND7
#define LEDS_1_DDR DDRB
#define LEDS_2_DDR DDRD
#define LEDS_3_DDR DDRD
#define LEDS_1_PORT PORTB
#define LEDS_2_PORT PORTD
#define LEDS_3_PORT PORTD

#define OUTPUT_TRANSMIT_PIN PIND1
#define OUTPUT_TRANSMIT_DDR DDRD
#define OUTPUT_RECEIVE_PIN PIND0
#define OUTPUT_RECEIVE_DDR DDRD
#define OUTPUT_RECEIVE_PORT PORTD


#endif /* PINCONFIGURATION_H_ */